<img style="float: left;;" src='Figures/alinco.png' height="100"/></a>

# <center> <font color= #000047>  Librería NumPy</font> </center>




NumPy es una poderosa librería de álgebra lineal para Python. Lo que lo hace tan importante es que casi todas las librerías en el ecosistema de <a href='https://pydata.org/'>PyData</a> (pandas, scipy, scikit-learn, etc.) utilizan NumPy como uno de sus principales componentes básicos. 

NumPy también es increíblemente rápido, ya que tiene enlaces a bibliotecas C.

Aquí repasaremos los conceptos básicos de NumPy.

## Usando NumPy


In [2]:
import numpy as np

print(np.__version__)

2.3.2



NumPy tiene muchas funciones y capacidades integradas. No veremos todos, nos centraremos en algunos de los aspectos más importantes de NumPy qué nos serán de utilidad en el curso como son: vectores, arreglos, matrices y generación de números aleatorios. 

# Arreglos en NumPy 

Los arreglos de NumPy son la principal forma en que utilizaremos esta librería a lo largo del curso. Los arreglos en NumPy se construyen de dos formas: vectores y matrices. Los vectores son matrices estrictamente unidimensionales (1D) y las matrices son elementos en 2D (pero se debe tener en cuenta que una matriz puede tener solo una fila o una columna) no son estrictamente cuadradas.

## Creando Arreglos en NumPy

### De una Lista de Python 

Podemos crear un arreglo directamente de una lista o listas de listas:



In [3]:
lista = [1,2,3,4,5]
arreglo = np.array(lista)
print(arreglo)
print(type(arreglo))

lista2=[[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(lista2)
print(matriz)
print(type(matriz))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [5]:
print(arreglo.shape)
print(matriz.shape) ##Devuelve el tamaño del arreglo o matriz

(3, 3)

In [7]:
matriz = np.array([[[1,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]]])
print(matriz.shape)

(2, 3, 3)


## Métodos incorporados en NumPy

Hay muchas formas de como generar arreglos usando métodos incorporados.

### arange

Devuelve valores espaciados uniformemente dentro de un intervalo dado. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [8]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### Creando arreglos de Ceros (zeros) y Unos (ones)

Podemos generar matrices de ceros ó unos. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [11]:
array = np.zeros(5)
print(array)

[0. 0. 0. 0. 0.]


In [13]:
array =np.zeros((5,2), dtype=int)
print(array)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [14]:
array = np.ones(5)
print(array)

[1. 1. 1. 1. 1.]


In [11]:
array = np.ones((5,5), dtype=int)
print(array)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### linspace 
Este método devuelve números espaciados uniformemente durante un intervalo especificado.[[referencia](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [15]:
np.linspace(0,20)

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [16]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `end

In [20]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

<font color=green>Note que `.linspace()` *incluye* el valor de paro. Para obtener un arreglo con fracciones comunes, hay que aumentar el numero de elementos:</font>

### eye

Mediante este método podemos crear la matriz identidad.[[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [24]:
np.eye(4,4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

## Random 
Numpy también tiene muchas formas de crear arreglos de números aleatorios:

### rand

Mediante este método podemos crear un arreglo de un tamaño dado con muestras aleatorias de una distribución uniforme en el intervalo ``[0, 1)``.[[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [27]:
np.random.rand(4) ##Crea un arreglo con numeros random generados uniformemente

array([0.55529595, 0.59640583, 0.5548905 , 0.90550374])

### randn

Este método devuelve una muestra (o muestras) de la distribución "normal estándar" [σ = 1] A diferencia de **rand**, que es uniforme, es más probable que aparezcan valores más cercanos a cero. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]


In [28]:
np.random.randn(5)## genera un arreglos con numeros randoom con una distribución normal

array([ 2.11246994, -0.30517081,  0.57381475,  0.13826595, -0.0206503 ])

### randint
Devuelve números enteros aleatorios de un intervalo `mínimo` (inclusive) a `máximo` (exclusivo).  [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [38]:
np.random.randint(1,100,20)

array([58, 33, 61, 25, 94,  6, 84, 77, 39, 16, 39, 54, 67, 18, 47, 63, 70,
       26, 25, 71], dtype=int32)

### seed
Se puede utilizar para establecer el estado aleatorio, de modo que se puedan reproducir los mismos resultados "aleatorios". [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

## Atributos y métodos de un Arreglo

Analicemos algunos atributos y métodos útiles para un arreglo:

In [41]:
arr = np.arange(25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


## Reshape
Devuelve una matriz que contiene los mismos datos con una nueva forma. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [42]:
print(arr.reshape(5,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [43]:
print(arr.reshape(1,25))
print(arr.reshape(25,1))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]


### max, min, argmax, argmin

Estos son métodos útiles para encontrar valores máximos o mínimos. O para encontrar el índice donde tenemos valores máximos o mínimos:

In [50]:
print(arr)
print(arr.max())
print(arr.min())
print(arr.argmax())
print(arr.argmin())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
24
0
24
0


## Shape

Shape es un atributo que tienen los arreglos (no un método): [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [51]:
print(arr.shape)

(25,)


### dtype

Podemos también obtener el tipo de datos del objeto en el arreglo. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [ ]:
print(arr.dtype)

int64


: 