<img style="float: left;;" src='Figures/alinco.png' height="100"/></a>

# <center> <font color= #000047> NumPy Indexación y selección</font> </center>




En este apartado veremos como seleccionar elementos o grupos de elementos de un arreglo.

In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


## Selección e indexación mediante Brackets
La forma más sencilla de elegir uno o algunos elementos de un arreglo es muy similar a las listas de Python:

In [4]:
print(arr[4])

4


In [6]:
arr2= arr[2:5]
print(arr2)

print(arr[::2])

[2 3 4]
[ 0  2  4  6  8 10]


## Broadcasting

Los arreglos en NumPy se diferencian de las listas normales de Python debido a su capacidad para reasignar valores. Con las listas, solo puede reasignar partes de una lista con partes nuevas del mismo tamaño y forma. Es decir, si quisiera reemplazar los primeros 5 elementos de una lista con un nuevo valor, tendría que pasar una nueva lista de 5 elementos. Con los arreglos de NumPy, podemos reasignar un solo valor a través de un conjunto más grande de valores:


In [7]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [8]:
arr[0:5] =100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [12]:
arr = np.arange(0,11)
slice_arr = arr[0:6]
print(slice_arr)

[0 1 2 3 4 5]


In [ ]:
slice_arr[:]=99 ##Se reeplazan los valores del arreglo original, lo hace por referencia
print(slice_arr)
print(arr)

[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]


Los datos no se copian, sólo es un pedazo del arreglo original.

In [15]:
arr2= arr.copy()

arr2 [0:6]=10

print(arr2)
print(arr)

[10 10 10 10 10 10  6  7  8  9 10]
[99 99 99 99 99 99  6  7  8  9 10]


## Indexación de un arreglo 2D (matrices)

Lo forma general es: **arr_2d[row][col]** o **arr_2d[row,col]**.

In [16]:
arr2d= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(arr2d[0,2])   #El primer elemento es el renglon, el segundo es la columna

3


In [ ]:
print(arr2d[:2,:2]) #Se puede indexar por submatrices

[[1 2]
 [4 5]]


In [25]:
print(arr2d[1:,1:]) 
print(arr2d[::2,::2])

[[5 6]
 [8 9]]
[[1 3]
 [7 9]]


## Más sobre indexación
Indexar una matriz 2D puede ser un poco confuso al principio, especialmente cuando se tiene un mator tamaño en la matriz.

Una imagen útil para entender el concepto de indexación:

<img src= 'Figures/numpy_indexing.png' width=500/> 

## Selección Condicional

Este es un concepto muy fundamental que nos servirá en la librería de Pandas más adelante, ¡asegúrate de entender esta parte!


In [26]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
arr>5

for item in arr>5:
    print(item)


print(arr[arr>5]) ##Imprime todos los elementos que cumplen la condición

False
False
False
False
False
True
True
True
True
True
[ 6  7  8  9 10]
