
<img style="float: left;;" src='Figures/alinco.png' height="100"/></a>

# <center> <font color= #000047>  Operaciones con NumPy</font> </center>



## Aritméticas

Podemos realizar fácilmente aritmeticas como *arreglo con arreglo* , o *escalar con arreglo*. Veamos algunos ejemplos: 

In [5]:
import numpy as np

l1=[1,2,3]
l2=[4,5,6]
print(l1+l2)

a1= np.array(l1)
a2= np.array(l2)
print(a1+a2)

print(2*a1)

print(a1.transpose())

[1, 2, 3, 4, 5, 6]
[5 7 9]
[2 4 6]
[1 2 3]


In [ ]:
# Crear una matriz aleatoria de números enteros de dimensión 4x2 -> A
# Crear una matriz aleatoria de números enteros de dimensión 2x6 -> B
# Realizar la multiplicación de Matrices C = A*B
# Realizar la multiplicación de Matrices C = B*A



In [8]:
A = np.random.randint(100, size=(4,2))
print(A)

[[80 26]
 [61 85]
 [ 4 53]
 [ 1 32]]


In [9]:
B= np.random.randint(100, size=(2,6))
print(B)

[[89 22 56 45 92  2]
 [ 2  7 40 10 12 12]]


In [ ]:
C= A@B #Con el @ se pueden multiplicar las matrices
print(C)
print(C.shape)

[[7172 1942 5520 3860 7672  472]
 [5599 1937 6816 3595 6632 1142]
 [ 462  459 2344  710 1004  644]
 [ 153  246 1336  365  476  386]]
(4, 6)


## Funciones universales en los Arreglos

NumPy viene con muchass [funciones universales en los arreglos](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, que son esencialmente operaciones matemáticas que se pueden aplicar al arreglo.<br>Veamos algunas funciones más comunes:

In [ ]:
print(np.sqrt(a1)) # Raiz cuadrada de cada elemento

[1.         1.41421356 1.73205081]


In [14]:
print(np.exp(a1))

[ 2.71828183  7.3890561  20.08553692]


In [15]:
print(np.sin(a1))

[0.84147098 0.90929743 0.14112001]


In [16]:
print(np.cos(a1))

[ 0.54030231 -0.41614684 -0.9899925 ]


In [17]:
print(np.log(a1))

[0.         0.69314718 1.09861229]


## Resumen de Estadística sobre Arreglos

NumPy también ofrece métodos estadísticos como <em> sum </em>, <em> mean </em> y <em> max </em>. 

In [19]:
print(a1.sum())

6


In [20]:
print(a1.mean())

2.0


## Lógica para el eje (axis)

Cuando trabajamos con arreglos bidimensionales, debemos considerar filas y columnas. En términos de un arreglo, el eje 0 (cero) es el eje horizontal (filas) y el eje 1 es el eje vertical (columnas). Los valores (0,1) corresponden al orden en el que método <tt> arr.shape </tt> da como salida.

Veamos cómo afecta esto a nuestros cálculos estadísticos resumidos de arriba.


Dando como entrada <tt>axis=0</tt>, estamos devolviendo la suma del arreglo a lo largo del eje vertical, esencialmente <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>

<img src='Figures/axis_logic.png' width=400/>

Esto nos dice que <tt>arr_2d</tt> tiene 3 filas y 4 columnas.

En <tt>arr_2d.sum(axis=0)</tt>, se sumó el primer elemento de cada fila, luego el segundo elemento y así sucesivamente.

Entonces, ¿qué debería <tt>arr_2d.sum(axis=1)</tt> regresar?

## Ejercicio 1


### Numpy

1. Crear un vector con valores de 10 a 49.
2. Elevar al cuadrado a aquellos números divisibles por 3.
3. Redimensionar ese vector en una matriz de 20x2.
4. Crear una nueva matriz de 2x10 y multiplicarla a la matriz anterior.
5. Obtener la transpuesta de la matriz resultante.

In [31]:
vector= np.arange(10,50) #Crear un vector con valores de 10 a 49.
print(vector)

for item in vector: #Elevar al cuadrado a aquellos números divisibles por 3.
    if item%3 ==0 :
        print(f"item:{item} -> {item**2}")

print(vector[vector%3==0]**2) #Elevar al cuadrado a aquellos números divisibles por 3.

print("Redimensionar ese vector en una matriz de 20x2.")
print(vector.reshape(20,2))




[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
item:12 -> 144
item:15 -> 225
item:18 -> 324
item:21 -> 441
item:24 -> 576
item:27 -> 729
item:30 -> 900
item:33 -> 1089
item:36 -> 1296
item:39 -> 1521
item:42 -> 1764
item:45 -> 2025
item:48 -> 2304
[ 144  225  324  441  576  729  900 1089 1296 1521 1764 2025 2304]
Redimensionar ese vector en una matriz de 20x2.
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]
 [40 41]
 [42 43]
 [44 45]
 [46 47]
 [48 49]]


In [ ]:
print("Crear una nueva matriz de 2x10 y multiplicarla a la matriz anterior.")
matriz= np.random.randint(100, size=(2,10))
print(matriz)
B=vector.reshape(20,2)
C= B@matriz
print(C)

#Obtener la transpuesta de la matriz resultante.
print(C.transpose())

Crear una nueva matriz de 2x10 y multiplicarla a la matriz anterior.
[[76 77 17  6 49 33 34 56 53 22]
 [64  5 24 38 79  9 23 24 72  9]]
[[1464  825  434  478 1359  429  593  824 1322  319]
 [1744  989  516  566 1615  513  707  984 1572  381]
 [2024 1153  598  654 1871  597  821 1144 1822  443]
 [2304 1317  680  742 2127  681  935 1304 2072  505]
 [2584 1481  762  830 2383  765 1049 1464 2322  567]
 [2864 1645  844  918 2639  849 1163 1624 2572  629]
 [3144 1809  926 1006 2895  933 1277 1784 2822  691]
 [3424 1973 1008 1094 3151 1017 1391 1944 3072  753]
 [3704 2137 1090 1182 3407 1101 1505 2104 3322  815]
 [3984 2301 1172 1270 3663 1185 1619 2264 3572  877]
 [4264 2465 1254 1358 3919 1269 1733 2424 3822  939]
 [4544 2629 1336 1446 4175 1353 1847 2584 4072 1001]
 [4824 2793 1418 1534 4431 1437 1961 2744 4322 1063]
 [5104 2957 1500 1622 4687 1521 2075 2904 4572 1125]
 [5384 3121 1582 1710 4943 1605 2189 3064 4822 1187]
 [5664 3285 1664 1798 5199 1689 2303 3224 5072 1249]
 [5944 3449 1746

: 

## Ejercicio 2

Se desea calcular el índice de masa corporal (IMC) de jugadores de un equipo de futbol. Los datos proporcionados corresponden a las listas de los nombres, altura y peso, tal como se muestra a continuación

In [ ]:
nombre= ['Bonifacio de Cifuentes',
'Ángel Machado Lara',
'Geraldo de Atienza',
'Onofre Posada Grande',
'Samu Cantón-Figuerola',
'Camilo Pol',
'Toni Galvez Lara',
'Lucho Manzano Rivas',
'Abraham Aroca',
'Anselmo Bartolomé Folch',
'Toni Inocencio Rozas Porras',
'Fausto Cortés-Arco',
'Baltasar Carreño Isern']

altura = [180, 215, 210, 210, 188, 176, 209, 200, 210, 188, 176, 209, 200]
peso = [69, 74, 72, 75, 68, 70, 71, 73, 69, 74, 72, 75, 68, 70, 71, 73]

El valor de IMC por cada jugador resulta de aplicar la fórmula:

$$IMC = \frac{peso(kg)}{altura(m)^2}$$

**Nota:** Los valores de altura están dados en centímetros por lo que deberá hacer laconversión a metros previo a la aplicación de la fórmula. Adicionalmente, una vez obtenido el IMC se solicita:

> a) Presentar el icm para cada jugador.

> b) Indicar en qué índice se encuentra el icm más alto y a qué jugador le pertenece.

> c) Calcular el promedio de los icm resultantes.

> d) Muestre los nombres de los jugadores en orden de su imc, desde el que tiene menorimc al que tiene mayor imc.