<img style="float: left;;" src='Figures/alinco.png' /></a>
    
# <center> <font color= #000047> Tarea 1: Eigenvectores y Eigenvalores</font>
___

Esta tarea consiste en calcular eigenvalores y eigenvectores de matrices siguiendo el calculo a mano, usando la librería numpy y sympy.

Los eigenvalores y eigenvectores son conceptos fundamentales en álgebra lineal y tienen aplicaciones en machine learning, física, ingeniería y más.

In [134]:
import numpy as np
import sympy as sym

Sea A una matriz de nxn con componentes reales, el número λ se denomina valor característico de A, si existe un vector diferente de cero V en los numeros complejos tal que  Av = λv.

El vector V se denomina vector característico de A
Procedimiento:

1.- Se encuentra P(λ) = det(A -λI)

2.- Se encuentran las raíces de P(λ)=0

3.-Se resuelve el sistema homogeneo (A -λI)V=0



In [135]:
def EigenVal_Vec(parMatriz):
    print(f"{"=="*10} Cálculo paso a paso {"=="*10}")
    print(f"1.- Se encuentra P(λ) = det(A -λI)")
    lambda_sym = sym.symbols('λ')
    print(f"   det(A -λI) =0")
    columns=parMatriz.shape[0]
    print(f"{"--"*10} λI {"--"*10}")
    I= np.eye(columns)
    Ilambda= lambda_sym*I
    print(f"λI = {Ilambda}")

    print(f"{"--"*10} A-λI {"--"*10}")
    AlamdaI=A-Ilambda
    print(f"A-λI = {AlamdaI}")

    print(f"{"--"*10} det(A -λI) {"--"*10}")
    res = sym.Matrix(AlamdaI)
    detRes= res.det()
    print(f" det(A -λI) = {detRes} = 0")
    soluciones = sym.solve(detRes, lambda_sym)
    print(f"2.- Se encuentran las raíces de P(λ)=0")
    print(f"  Eigen Valores: {[float(sol) for sol in soluciones]}")

    print("3.-Se resuelve el sistema homogeneo (A -λI)V=0")
    vectorCaracteristico=[]
    for i in range(columns):
        vectorCaracteristico.append(sym.symbols('X'+ str(i + 1)))

   
    for val in soluciones:
        print(f"{"--"*10} (A -λI)=V  ----- λ={float(val)} {"--"*10}")
        print(f"{parMatriz} - {float(val)} * {I} = {vectorCaracteristico}")
        res=parMatriz-(float(val) * I)
        print(f"{"--"*10} (A -λI)V=0 {"--"*10}")
        print(f"{res} = ll0")
        print(f"{res} * {vectorCaracteristico} = 0")
        print(f"{"--"*15}")
        print(f"{res * vectorCaracteristico} = 0")
        ecuaciones = res * vectorCaracteristico
        print(f"{"--"*10} Ecuacinoes {"--"*10}")
        for i in range(columns):
            ecuacionstr=""
            ecuacion=""
            for j in range(columns):
               ecuacionstr += f"{ecuaciones[i,j]} + "
            
            ecuacion = ecuacionstr.rstrip(' + ') + " = 0"
            print(f"{ecuacion}")

        U, S, Vt = np.linalg.svd(res)
        null_space = Vt[-1:]  # El último vector singular derecho

        print(f"Eigen Vector: {null_space[0]}")


In [136]:

def CalculaEigenVal_Vec(parMatriz):

    print(f"{"=="*15} Numpy {"=="*15}")
    eiVal, eiVec = np.linalg.eig(parMatriz)

    print(f"Eigenvalores: {eiVal}")
    print(f"Eigenvectores: {eiVec}")


    print(f"{"=="*15} Sympy {"=="*15}")
    A = sym.Matrix(parMatriz)
    eiVal = A.eigenvals()
    eiVec = A.eigenvects()
    print(f"Eigenvalores: {eiVal}")
    print(f"Eigenvectores: {eiVec}")

    EigenVal_Vec(parMatriz)

**1. Calcula los eigenvalores y eigenvectores de la siguiente matriz:**

$$A = \begin{bmatrix} 4 & 2 \\ 1 & 3 \end{bmatrix}$$

In [137]:
A = np.array([[4, 2],
              [1, 3]])

CalculaEigenVal_Vec(A)

============================== Numpy ==============================
Eigenvalores: [5. 2.]
Eigenvectores: [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
============================== Sympy ==============================
Eigenvalores: {5: 1, 2: 1}
Eigenvectores: [(2, 1, [Matrix([
[-1],
[ 1]])]), (5, 1, [Matrix([
[2],
[1]])])]
==================== Cálculo paso a paso ====================
1.- Se encuentra P(λ) = det(A -λI)
   det(A -λI) =0
-------------------- λI --------------------
λI = [[1.0*λ 0]
 [0 1.0*λ]]
-------------------- A-λI --------------------
A-λI = [[4 - 1.0*λ 2]
 [1 3 - 1.0*λ]]
-------------------- det(A -λI) --------------------
 det(A -λI) = 1.0*λ**2 - 7.0*λ + 10 = 0
2.- Se encuentran las raíces de P(λ)=0
  Eigen Valores: [2.0, 5.0]
3.-Se resuelve el sistema homogeneo (A -λI)V=0
-------------------- (A -λI)=V  ----- λ=2.0 --------------------
[[4 2]
 [1 3]] - 2.0 * [[1. 0.]
 [0. 1.]] = [X1, X2]
-------------------- (A -λI)V=0 --------------------
[[2. 2.]
 [1. 1

**2. Calcula los eigenvalores y eigenvectores de la siguiente matriz:**

$$B = \begin{bmatrix} 2 & 0 \\ 0 & 5 \end{bmatrix}$$

In [138]:
A = np.array([[2, 0],
              [0, 5]])

CalculaEigenVal_Vec(A)


============================== Numpy ==============================
Eigenvalores: [2. 5.]
Eigenvectores: [[1. 0.]
 [0. 1.]]
============================== Sympy ==============================
Eigenvalores: {2: 1, 5: 1}
Eigenvectores: [(2, 1, [Matrix([
[1],
[0]])]), (5, 1, [Matrix([
[0],
[1]])])]
==================== Cálculo paso a paso ====================
1.- Se encuentra P(λ) = det(A -λI)
   det(A -λI) =0
-------------------- λI --------------------
λI = [[1.0*λ 0]
 [0 1.0*λ]]
-------------------- A-λI --------------------
A-λI = [[2 - 1.0*λ 0]
 [0 5 - 1.0*λ]]
-------------------- det(A -λI) --------------------
 det(A -λI) = 1.0*λ**2 - 7.0*λ + 10 = 0
2.- Se encuentran las raíces de P(λ)=0
  Eigen Valores: [2.0, 5.0]
3.-Se resuelve el sistema homogeneo (A -λI)V=0
-------------------- (A -λI)=V  ----- λ=2.0 --------------------
[[2 0]
 [0 5]] - 2.0 * [[1. 0.]
 [0. 1.]] = [X1, X2]
-------------------- (A -λI)V=0 --------------------
[[0. 0.]
 [0. 3.]] = ll0
[[0. 0.]
 [0. 3.]] * [X1, X2

**3. Eigenvalores y eigenvectores de una matriz 3x3**

Calcula los eigenvalores y eigenvectores de la siguiente matriz:

$$C = \begin{bmatrix} 1 & 2 & 3 \\ 0 & 4 & 5 \\ 0 & 0 & 6 \end{bmatrix}$$

In [139]:
A = np.array([[1,2,3],
              [0,4,5],
              [0,0,6]])

CalculaEigenVal_Vec(A)

============================== Numpy ==============================
Eigenvalores: [1. 4. 6.]
Eigenvectores: [[1.         0.5547002  0.51084069]
 [0.         0.83205029 0.79818857]
 [0.         0.         0.31927543]]
============================== Sympy ==============================
Eigenvalores: {6: 1, 4: 1, 1: 1}
Eigenvectores: [(1, 1, [Matrix([
[1],
[0],
[0]])]), (4, 1, [Matrix([
[2/3],
[  1],
[  0]])]), (6, 1, [Matrix([
[8/5],
[5/2],
[  1]])])]
==================== Cálculo paso a paso ====================
1.- Se encuentra P(λ) = det(A -λI)
   det(A -λI) =0
-------------------- λI --------------------
λI = [[1.0*λ 0 0]
 [0 1.0*λ 0]
 [0 0 1.0*λ]]
-------------------- A-λI --------------------
A-λI = [[1 - 1.0*λ 2 3]
 [0 4 - 1.0*λ 5]
 [0 0 6 - 1.0*λ]]
-------------------- det(A -λI) --------------------
 det(A -λI) = -1.0*λ**3 + 11.0*λ**2 - 34.0*λ + 24 = 0
2.- Se encuentran las raíces de P(λ)=0
  Eigen Valores: [1.0, 4.0, 6.0]
3.-Se resuelve el sistema homogeneo (A -λI)V=0
----------

-------------------- Ecuacinoes --------------------
0 + 2.0*X2 + 3.0*X3 = 0
0 + 3.0*X2 + 5.0*X3 = 0
0 + 0 + 5.0*X3 = 0
Eigen Vector: [1. 0. 0.]
-------------------- (A -λI)=V  ----- λ=4.0 --------------------
[[1 2 3]
 [0 4 5]
 [0 0 6]] - 4.0 * [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] = [X1, X2, X3]
-------------------- (A -λI)V=0 --------------------
[[-3.  2.  3.]
 [ 0.  0.  5.]
 [ 0.  0.  2.]] = ll0
[[-3.  2.  3.]
 [ 0.  0.  5.]
 [ 0.  0.  2.]] * [X1, X2, X3] = 0
------------------------------
[[-3.0*X1 2.0*X2 3.0*X3]
 [0 0 5.0*X3]
 [0 0 2.0*X3]] = 0
-------------------- Ecuacinoes --------------------
-3.0*X1 + 2.0*X2 + 3.0*X3 = 0
0 + 0 + 5.0*X3 = 0
0 + 0 + 2.0*X3 = 0
Eigen Vector: [-5.54700196e-01 -8.32050294e-01  1.11022302e-16]
-------------------- (A -λI)=V  ----- λ=6.0 --------------------
[[1 2 3]
 [0 4 5]
 [0 0 6]] - 6.0 * [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] = [X1, X2, X3]
-------------------- (A -λI)V=0 --------------------
[[-5.  2.  3.]
 [ 0. -2.  5.]
 [ 0.  0.  0.]] = ll0


**4. Calcula los eigenvalores y eigenvectores de la siguiente matriz:**

$$D = \begin{bmatrix} 0 & 1 \\ -2 & -3 \end{bmatrix}$$

In [140]:
A = np.array([[0, 1],
              [-2, -3]])

CalculaEigenVal_Vec(A)

============================== Numpy ==============================
Eigenvalores: [-1. -2.]
Eigenvectores: [[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]
============================== Sympy ==============================
Eigenvalores: {-1: 1, -2: 1}
Eigenvectores: [(-2, 1, [Matrix([
[-1/2],
[   1]])]), (-1, 1, [Matrix([
[-1],
[ 1]])])]
==================== Cálculo paso a paso ====================
1.- Se encuentra P(λ) = det(A -λI)
   det(A -λI) =0
-------------------- λI --------------------
λI = [[1.0*λ 0]
 [0 1.0*λ]]
-------------------- A-λI --------------------
A-λI = [[-1.0*λ 1]
 [-2 -1.0*λ - 3]]
-------------------- det(A -λI) --------------------


 det(A -λI) = 1.0*λ**2 + 3.0*λ + 2 = 0
2.- Se encuentran las raíces de P(λ)=0
  Eigen Valores: [-2.0, -1.0]
3.-Se resuelve el sistema homogeneo (A -λI)V=0
-------------------- (A -λI)=V  ----- λ=-2.0 --------------------
[[ 0  1]
 [-2 -3]] - -2.0 * [[1. 0.]
 [0. 1.]] = [X1, X2]
-------------------- (A -λI)V=0 --------------------
[[ 2.  1.]
 [-2. -1.]] = ll0
[[ 2.  1.]
 [-2. -1.]] * [X1, X2] = 0
------------------------------
[[2.0*X1 1.0*X2]
 [-2.0*X1 -1.0*X2]] = 0
-------------------- Ecuacinoes --------------------
2.0*X1 + 1.0*X2 = 0
-2.0*X1 + -1.0*X2 = 0
Eigen Vector: [-0.4472136   0.89442719]
-------------------- (A -λI)=V  ----- λ=-1.0 --------------------
[[ 0  1]
 [-2 -3]] - -1.0 * [[1. 0.]
 [0. 1.]] = [X1, X2]
-------------------- (A -λI)V=0 --------------------
[[ 1.  1.]
 [-2. -2.]] = ll0
[[ 1.  1.]
 [-2. -2.]] * [X1, X2] = 0
------------------------------
[[1.0*X1 1.0*X2]
 [-2.0*X1 -2.0*X2]] = 0
-------------------- Ecuacinoes --------------------
1.0*X1 + 1.0*X2 = 0
-2.0*

**5. Crea una matriz cuadrada aleatoria de tamaño 4x4 y calcula sus eigenvalores y eigenvectores.**

In [150]:
#A = np.random.rand(4, 4)
A = np.array([[1, 1,1,2],
              [1,1,1, 1],
              [1, 2,1,2],
              [1, 1,1,1]])
CalculaEigenVal_Vec(A) 

============================== Numpy ==============================
Eigenvalores: [ 4.64575131e+00 -6.45751311e-01  5.66121701e-09 -5.66121703e-09]
Eigenvectores: [[-5.17096649e-01  2.11951335e-01  7.07106783e-01 -7.07106779e-01]
 [-4.25506244e-01 -3.86360928e-01 -8.00616995e-09 -8.00616984e-09]
 [-6.08687054e-01  8.10263598e-01 -7.07106779e-01  7.07106783e-01]
 [-4.25506244e-01 -3.86360928e-01  4.00308481e-09  4.00308504e-09]]
============================== Sympy ==============================
Eigenvalores: {2 - sqrt(7): 1, 2 + sqrt(7): 1, 0: 2}
Eigenvectores: [(0, 2, [Matrix([
[-1],
[ 0],
[ 1],
[ 0]])]), (2 - sqrt(7), 1, [Matrix([
[   1/3 - sqrt(7)/3],
[                 1],
[-2*sqrt(7)/3 - 1/3],
[                 1]])]), (2 + sqrt(7), 1, [Matrix([
[   1/3 + sqrt(7)/3],
[                 1],
[-1/3 + 2*sqrt(7)/3],
[                 1]])])]
==================== Cálculo paso a paso ====================
1.- Se encuentra P(λ) = det(A -λI)
   det(A -λI) =0
-------------------- λI ----------